### ISSUE TITLE
CUDA fails to compile on linux-ppc64le

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/libnd4j#188]
I still get this error when building libnd4j for CUDA on the machine that we have access to:
```
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
```
Looks like CUDA 7.5 doesn't support the libraries used by GCC on that machine...

**Comment by raver119** [comment]
That's pretty suspicious, because IBM guys have compiled it. And string.h complaint isnt a CUDA include. Can you show full output log?

**Comment by saudet** [comment]
Yes, a different team have compiled it, but we don't know their config. Full log? It's not relevant, and it's like 70 megs, but let me send that through Google Drive.

**Comment by raver119** [comment]
Post it to google drive please, i'll read through it, maybe i'll see something viable there, maybe no.

**Comment by agibsonccc** [comment]
Is this still true?

**Comment by saudet** [comment]
Yes, doesn't compile on 16.04, only 14.04...

**Comment by raver119** [comment]
I've also heard some complaints about 16.04 and cuda, for x86 arch. But they were pretty general, and didn't end up as issue
